In [1]:
import numpy as np
import pandas as pd

In [4]:
npr = pd.read_csv('C:\\Users\\Admin\\Jose_Portilo_NLP_Course\\UPDATED_NLP_COURSE\\05-Topic-Modeling\\npr.csv')

In [5]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [8]:
#npr['Article'][1]
len(npr)

11992

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
#
# max_df : float in range [0.0, 1.0] or int, default=1.0
#     When building the vocabulary ignore terms that have a document
#     frequency strictly higher than the given threshold (corpus-specific
#     stop words).

# min_df : float in range [0.0, 1.0] or int, default=1
#     When building the vocabulary ignore terms that have a document
#     frequency strictly lower than the given threshold. This value is also
#     called cut-off in the literature.
cv = CountVectorizer(max_df = 0.9, min_df = 2, stop_words = 'english')

In [12]:
dtm = cv.fit_transform(npr['Article'])

In [13]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [14]:
from sklearn.decomposition import LatentDirichletAllocation

In [15]:
lda = LatentDirichletAllocation(n_components = 7, random_state = 42)

In [16]:
lda.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=7, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [20]:
# Grab the vovabulary of words

#Grab the topics



In [21]:
# Grab the vovabulary of words

In [23]:
len(cv.get_feature_names())

54777

In [25]:
cv.get_feature_names()[5643]

'bewildered'

In [26]:
type(cv.get_feature_names())

list

In [31]:
import random 

random_word_id = random.randint(0, 54777)

cv.get_feature_names()[random_word_id]

'truce'

In [32]:
len(lda.components_)

7

In [33]:
type(lda.components_)

numpy.ndarray

In [34]:
lda.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [35]:
single_topic = lda.components_[0]

In [36]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [39]:
# Demonstration of argsort()
arr = np.array([10, 200, 1])
print(arr)
arr.argsort()

[ 10 200   1]


array([2, 0, 1], dtype=int64)

In [41]:
# ARGSORT --> INdex position sorted from LEAST to GREATEST
# TOP 10 values (10 greatest values) are
# Last 10 values of Argsort()
single_topic.argsort()[-10:] # grab the last 10 values of argsort()

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [42]:
top_twenty_words = single_topic.argsort()[-20:]

In [43]:
for index in top_twenty_words:
    print(cv.get_feature_names()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [44]:
#Grab the highest probability words per topic

In [46]:
for i, topic in enumerate(lda.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{i}')
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




THE TOP 15 WORDS FOR TOPIC #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




THE TOP 15 WORDS FOR TOPIC #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




THE TOP 15 WORDS FOR TOPIC #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




THE TOP 15 WORDS FOR TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




THE TOP 15 WORDS FOR TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know'

In [47]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [48]:
topic_results = lda.transform(dtm)

In [49]:
topic_results.shape

(11992, 7)

In [51]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [52]:
npr['Topic'] = topic_results.argmax(axis = 1)

In [55]:
npr.head(20)

Article  Topic
0   In the Washington of 2016, even when the polic...      1
1     Donald Trump has used Twitter  —   his prefe...      1
2     Donald Trump is unabashedly praising Russian...      1
3   Updated at 2:50 p. m. ET, Russian President Vl...      1
4   From photography, illustration and video, to d...      2
5   I did not want to join yoga class. I hated tho...      3
6   With a   who has publicly supported the debunk...      3
7   I was standing by the airport exit, debating w...      2
8   If movies were trying to be more realistic, pe...      3
9   Eighteen years ago, on New Year’s Eve, David F...      2
10  For years now, some of the best, wildest, most...      5
11  For years now, some of the best, wildest, most...      5
12  The Colorado River is like a giant bank accoun...      2
13  For the last installment of NPR’s holiday reci...      2
14  Being overweight can raise your blood pressure...      3
15  Who’s the YouTube star of 2016? Adele singing ...      5
16  Here’s a quick roundup of some of the   you ma...      2
17  Ben Johnston doesn’t follow the rules of music...      5
18  David Bowie, Prince and George Michael are all...      5
19  In November, the typically straitlaced Office ...      1