In [2]:
import pandas as pd
import numpy as np
import sklearn.model_selection as model_selection
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn.svm import SVC

In [9]:
data = pd.read_csv('C:\\Users\\Admin\\Desktop\\data sets\\Social_Network_Ads.csv')

In [10]:
real_x = data.iloc[:, [2,3]].values
real_y = data.iloc[:, 4].values


In [11]:
train_x, test_x, train_y, test_y = model_selection.train_test_split(real_x, real_y, test_size=0.25, random_state=0)

In [12]:
s_c = StandardScaler()
train_x = s_c.fit_transform(train_x)
test_x = s_c.fit_transform(test_x)
#train_x

In [13]:
import sklearn.ensemble as ensemble

In [14]:
clf = ensemble.RandomForestClassifier(n_estimators=100, oob_score= True)

In [15]:
clf.fit(train_x, train_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [16]:
pred_y = clf.predict(test_x)
pred_y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [17]:
test_y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [18]:
clf.predict_proba(test_x)

array([[0.92, 0.08],
       [1.  , 0.  ],
       [0.88, 0.12],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.12, 0.88],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.99, 0.01],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.12, 0.88],
       [0.56, 0.44],
       [1.  , 0.  ],
       [0.16, 0.84],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.39, 0.61],
       [0.93, 0.07],
       [0.03, 0.97],
       [0.99, 0.01],
       [0.35, 0.65],
       [0.97, 0.03],
       [0.97, 0.03],
       [0.99, 0.01],
       [0.95, 0.05],
       [0.98, 0.02],
       [0.87, 0.13],
       [0.09, 0.91],
       [0.99, 0.01],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.03, 0.97],
       [0.92, 0.08],
       [0.94, 0.06],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.28, 0.72],
       [1.  , 0.  ],
       [0.9 , 0.1 ],
       [0.12,

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
c_m = confusion_matrix(test_y, pred_y)
c_m

array([[63,  5],
       [ 3, 29]], dtype=int64)

In [ ]:
#this will show error, dont run
#pd.series(clf.feature_importances_,index=training_x.columns).sort_values(ascending=False)

In [21]:
clf.oob_score_

0.8833333333333333

In [22]:
for i in [100, 200, 300]:
    clf= ensemble.RandomForestClassifier(n_estimators = i, oob_score= True, n_jobs=-1)
    clf.fit(train_x, train_y)
    print("oob score for {} tree is {}".format(i, clf.oob_score_))
    

oob score for 100 tree is 0.8766666666666667
oob score for 200 tree is 0.8866666666666667
oob score for 300 tree is 0.8866666666666667


In [23]:
import sklearn.metrics as metrics

In [24]:
for i in [100, 200, 300]:
    clf = ensemble.RandomForestClassifier(n_estimators= i, oob_score=True, n_jobs=-1)
    clf.fit(train_x, train_y)
    pred_oob = clf.oob_decision_function_[:, 1]
    auc = metrics.roc_auc_score(test_y, pred_y)
    print("auc score {} tree is {}".format(i,auc))

auc score 100 tree is 0.9163602941176471
auc score 200 tree is 0.9163602941176471
auc score 300 tree is 0.9163602941176471


In [25]:
result = pd.DataFrame({'actual': test_y, 'predicted': pred_y})

In [26]:
result.head(14)

actual  predicted
0        0          0
1        0          0
2        0          0
3        0          0
4        0          0
5        0          0
6        0          0
7        1          1
8        0          0
9        0          1
10       0          0
11       0          0
12       0          0
13       0          0

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(test_y, pred_y)

0.92