In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn import datasets

In [3]:
#loading the dataset
dig =datasets.load_digits()

In [4]:
#some visualization
dig.data[:2]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.]])

In [5]:
dig.target

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
#curently it has 64 attributes after performing pca it will decrease
dig.data.shape

(1797, 64)

In [7]:
dig.target.shape

(1797,)

In [8]:
#splitting training and testing data
from sklearn.model_selection import train_test_split

train_img, test_img, train_lbl, test_lbl = train_test_split(dig.data, dig.target, test_size=0.3, random_state=0)

In [9]:
#standarizing our train_img
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(train_img)

#apply transform to both the training and testing set
train_img = scaler.transform(train_img)
test_img = scaler.transform(test_img)

In [10]:
#visualig after standarization
train_img[:1]

array([[ 0.        , -0.34338378, -1.09642621, -0.88717562, -0.42825571,
         1.43845406,  0.49363934, -0.12501886, -0.05963551, -0.3151569 ,
         0.47849512,  0.21918793, -0.28691819,  0.6197714 ,  1.76922825,
        -0.12614188, -0.03992024,  0.96822696,  1.0921471 ,  0.14757351,
         0.14198996,  1.32778473,  0.70793513, -0.11294863, -0.02821663,
         0.80906081,  1.10876452,  1.21974443,  0.98975536,  0.26282114,
        -0.64074225, -0.03992024,  0.        , -0.67349682, -0.41365522,
        -0.16812017,  0.62783539,  0.5664439 , -0.82668859,  0.        ,
        -0.06209797, -0.53059473, -1.06319169, -0.66713857,  1.31816087,
        -0.55060546, -0.7726095 , -0.09516311, -0.04237744, -0.40873595,
        -1.33984381,  1.01453563, -0.30892748, -1.43653873, -0.7348467 ,
        -0.19859912, -0.02821663, -0.30739208, -0.90153224, -0.01866477,
        -1.98373642, -1.12193961, -0.48894777, -0.18556033]])

In [11]:
from sklearn.decomposition import PCA

In [12]:
#making pca object
pca = PCA(.95)

#It means sklearn will choose minimum no. of priincipal componensts such
#that 95% of the variance is retained
#change the value in it to see the increment or decrement in the number of
#attributes left after performing PCA and also the change in the value of 
#lr.score

In [13]:
#performing pca on our data
pca.fit(train_img)

PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [14]:
#againing transforming our data with pca
train_img = pca.transform(train_img)
test_img = pca.transform(test_img)

In [22]:
#After performing pca we are left with only 40 attributes which can explain
#95% of the variation in our data
train_img.shape

(1257, 40)

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
#default solver is slow which is why it was changed to 'lbfgs'
lr = LogisticRegression(solver = 'lbfgs')

In [18]:
#training our model
lr.fit(train_img, train_lbl)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
#prediting the test_img
lr.predict(test_img[9:20])

array([5, 2, 8, 6, 6, 6, 6, 1, 0, 5, 8])

In [28]:

test_lbl[9:20]

array([5, 2, 8, 6, 6, 6, 6, 1, 0, 5, 8])

In [21]:
lr.score(test_img, test_lbl)

0.95